[package]
name = "yuantuan"
version = "0.1.0"
edition = "2021"

[dependencies]
yuantuan-core = { path = "../core" }
yuantuan-adapter-qq = { path = "../adapter-qq" }
yuantuan-webui = { path = "../webui" }
yuantuan-plugin-hello = { path = "../../plugins/hello", optional = true }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
sqlx.workspace = true
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"

[features]
default = ["plugin-hello"]
plugin-hello = ["dep:yuantuan-plugin-hello"]
